MODEL:
  TYPE: vssm
  NAME: vssm1_tiny_0230
  DROP_PATH_RATE: 0.2
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 5, 2 ]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_CONV: 3
    SSM_CONV_BIAS: false
    SSM_FORWARDTYPE: "v05_noz" # v3_noz
    MLP_RATIO: 4.0
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
TRAIN:
  EPOCHS: 200
  BASE_LR: 1e-3
  WARMUP_LR: 1e-4
  MIN_LR: 1e-5
TEST:
  CROP: False
  CROP_TYPE: "center"
  FIVE_CROP: True
  EVAL_SAVE: True